### ISSUE TITLE
OpenGraph meta tags not fetched

### ISSUE THREAD

**Issue by wit03** [smastrom/headless-gatsby-multilang#15] opened 2022-08-13 14:24 UTC
Seems like all of meta tag related to SEO is not working as expected, I have tried to identify the problem but still don't know exactly what is happenning. 

You can use [Facebook Share Debugger](https://developers.facebook.com/tools/debug ) to test it out, there is no information about the blog or the site shown.

Here's what I've found:
- Meta tag is not appear in `public/index.html` after `gatsby build`
- Meta tag do appear in dev tools when inspecting the demo site.

Here's possible cause of problems:
- there are too many content before <meta> so Facebook Share didn't grap it. [related](https://github.com/gatsbyjs/gatsby/issues/22908) 
- react-helmet make <meta> dynamically write to the DOM after render everyting. [related](https://github.com/gatsbyjs/gatsby/issues/10414)

**Comment by smastrom** [comment] 2022-08-13 17:16
I believe something's broken with react-helmet since latest Gatsby updates. It always worked but yeah, right now is definitely not working anymore. Thank you for reporting this issue.

Gatsby recently released its own Head package, planning to deprecate react-helmet soon.

I tried to migrate the starter from react-helmet to Gatsby Head, but unfortunately, its API is limited as it is not possible to switch/inject natively the lang attribute to the html tag without hacks.

I will try to investigate and let you know as soon as possible.

Thank you again,

Simone

**Comment by wit03** [comment] 2022-08-13 17:20
Thanks,

Can you remember the lastest version of gatsby and react-helmet that make this problem resolve? I need to use this project as soon as possible.

**Comment by smastrom** [comment] 2022-08-13 19:04
Hi @wit03, thank you for reporting this issue. Apparently it was related to a condition to prevent flickerings when restoring darkMode from the storage.

I have just merged the fix branch and the issue is now vanished. You can just repeat the installation so that gatsby new will fetch the last commit.

Enjoy and thank you again for reporting the issue!


![Schermata 2022-08-13 alle 21 01 50](https://user-images.githubusercontent.com/78644132/184507340-90c74431-fd62-470d-9904-422128f002a7.png)


![Schermata 2022-08-13 alle 21 02 21](https://user-images.githubusercontent.com/78644132/184507341-5c198793-d0d1-4399-988a-68de4e2c017f.png)

**Closed** 2022-08-13 19:06 UTC
